USE FBMDB;

--SELECT table_name
--FROM INFORMATION_SCHEMA.TABLES
--WHERE table_type = 'BASE TABLE';

--INSERT INTO CURRENCIES
--SELECT * FROM CurrenciesData;

--EXEC sp_rename 'PRODUCTS.ProductName', 'Model', 'Column';

--ALTER TABLE BUSINESSES
--DROP COLUMN Signatuer;

--DROP TABLE CurrenciesData


--ALTER TABLE USERS
--ADD Permission int not null;




ALTER TABLE BILLS
ALTER COLUMN Amount MONEY;


SELECT * FROM CURRENCIES
SELECT * FROM BRANDS
SELECT * FROM COLORS
SELECT * FROM STORAGES
SELECT * FROM TERMS
SELECT * FROM PRODUCTS
SELECT * FROM PEOPLE
SELECT * FROM CUSTOMERS
SELECT * FROM USERS
SELECT * FROM BUSINESSES
SELECT * FROM BILLS
SELECT * FROM BILLS_BODY
SELECT * FROM PAYMENTS


SELECT 1 BrandName FROM BRANDS WHERE BrandName = 'Apple'

SELECT 
ProductID,
BRANDS.BrandName, 
PRODUCTS.Model, 
COLORS.ColorName,
STORAGES.StorageCapacity, 
PRODUCTS.Condition,
TERMS.Description, 
CURRENCIES.Code,
PRODUCTS.PurchaPrice, 
PRODUCTS.ProductImage,
PRODUCTS.Quality
FROM PRODUCTS
JOIN BRANDS ON PRODUCTS.BrandID = BRANDS.BrandID
JOIN COLORS ON PRODUCTS.ColorID= COLORS.ColorID
JOIN STORAGES ON PRODUCTS.StorageID = STORAGES.StorageID
JOIN TERMS ON PRODUCTS.TermID = TERMS.TermID
JOIN CURRENCIES ON PRODUCTS.CurrencyID = CURRENCIES.CurrencyID



SELECT COUNT(*) as Total FROM PEOPLE WHERE Gendor = 1


SELECT COUNT(*) as Total 
FROM CUSTOMERS
JOIN PEOPLE ON CUSTOMERS.PersonID = PEOPLE.PersonID
Group by Gendor HAVING Gendor = 0



SELECT 
CUSTOMERS.CustomerID, CUSTOMERS.PersonID, PEOPLE.FirstName, PEOPLE.SecondName, PEOPLE.LastName,
PEOPLE.Email, PEOPLE.Address, PEOPLE.Phone, PEOPLE.Gendor
FROM CUSTOMERS
JOIN PEOPLE ON CUSTOMERS.PersonID = PEOPLE.PersonID
where CustomerID = 2;


--DELETE CUSTOMERS WHERE CUSTOMERS.CustomerID = 8
--DELETE PEOPLE WHERE PersonID = 11


SELECT BILLS.*, BILLS_BODY.BillID, ProductID,  Quantity, SellingPrice, BILLS_BODY.CurrencyID 
FROM BILLS
JOIN BILLS_BODY ON BILLS.BillID = BILLS_BODY.BillID

--delete from BILLS_BODY
--delete from bills


SELECT
From_Business = BusinessName,
To_Customer = FirstName + ' '+ SecondName + ' ' + LastName,
BILLS.Amount, Discount, Date, BillStatus, CurrencyRate, Code,
Created_By_User = USERS.Username
FROM BILLS
JOIN BUSINESSES ON BILLS.FromBusinessID = BUSINESSES.BusinessID
JOIN CURRENCIES ON BILLS.CurrencyID= CURRENCIES.CurrencyID
JOIN USERS ON BILLS.CreatedByUserID = USERS.PersonID 
JOIN CUSTOMERS ON BILLS.ToCustomerID = CUSTOMERS.CustomerID
JOIN PEOPLE ON CUSTOMERS.PersonID = PEOPLE.PersonID


SELECT Bills.*, FirstName + ' ' + SecondName +' '+ LastName AS Customer
FROM BILLS 
JOIN CUSTOMERS ON BILLS.ToCustomerID = CUSTOMERS.CustomerID 
JOIN PEOPLE ON CUSTOMERS.PersonID = PEOPLE.PersonID


SELECT Model, Quantity, SellingPrice, Code
FROM BILLS_BODY 
JOIN PRODUCTS ON BILLS_BODY.ProductID = PRODUCTS.ProductID
JOIN CURRENCIES ON BILLS_BODY.CurrencyID = CURRENCIES.CurrencyID
WHERE BILLS_BODY.BillID = 23



SELECT SUM(BILLS.Amount) AS Total FROM BILLS
WHERE Date BETWEEN '2024-9-12' AND '2024-9-13';